version: "3"
services:
  app:
    image: tonytunde2012/image_aug:latest
    ports:
      - "8000:${PORT}"
    environment:
      - PORT=${PORT}
      - MAX_CONTENT_LENGTH=${MAX_CONTENT_LENGTH}
      - SEND_FILE_MAX_AGE_DEFAULT=${SEND_FILE_MAX_AGE_DEFAULT}
    restart: always
  
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    environment:
      WATCHTOWER_CLEANUP: 'true'
      WATCHTOWER_REMOVE_VOLUMES: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always