version: "3"
services:
  app:
    image: tonytunde2012/image_aug:latest
    ports:
      - "8000:8000"
    restart: always
  
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    environment:
      WATCHTOWER_CLEANUP: 'true'
      WATCHTOWER_REMOVE_VOLUMES: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always